#!/usr/bin/env bash
# This script demonstrates handling signals

# Trap signals
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

# Create PID file
echo $$ > /var/run/myscript.pid

# Display To infinity and beyond indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
