#!/usr/bin/env bash
# Find and terminate the '7-highlander' process

pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
    kill -s SIGKILL "$pid"
    echo "Killed 7-highlander process with PID $pid"
else
    echo "Process 7-highlander not found"
fi
