#!/usr/bin/env bash

# This script displays "Best School" 10 times, and for the 
# 9th iteration, it displays "Hi" on a new line

counter=0

while [ $counter -lt 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
        echo "Best School"
    ((counter++))
done
