#!/usr/bin/env bash
# This script displays the content of the current directory
# in a list format, showing only the part of the name after the first dash

# Iterate over non-hidden files in the current directory
for file in *;
do
    if [ -f "$file" ];
    then
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done
